apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  annotations:
    description: Runs sourcegraph executor replicas for batch changes and codeintel auto indexing.
    kubectl.kubernetes.io/default-container: executor
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: executor
spec:
  selector:
    matchLabels:
      app: executor
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: executor
    spec:
      containers:
        - name: executor
          image: index.docker.io/sourcegraph/executor:5.0.6@sha256:f78a0ba3d84941ec3577f19075e935bec34a9bfaa9dcb85908142fff017e9d6d
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /usr/bin/pgrep
                - /usr/local/bin/executor
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /usr/bin/pgrep
                - /usr/local/bin/executor
            periodSeconds: 5
          terminationMessagePolicy: FallbackToLogsOnError
          # Refer to https://docs.sourcegraph.com/admin/executors/deploy_executors_binary#step-2-setup-environment-variables on how to populate these variables
          envFrom:
            - configMapRef:
                name: executor-config
          volumeMounts:
            - mountPath: /scratch
              name: executor-scratch
        - name: dind
          image: index.docker.io/sourcegraph/dind:5.0.6@sha256:51c810393d5959bf07365b410f129580a48427a8a78a881735a9da74943dc18a
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
            - 'dockerd'
            - '--tls=false'
            - '--mtu=1200'
            - '--registry-mirror=http://private-docker-registry:5000'
            - '--host=tcp://0.0.0.0:2375'
          livenessProbe:
            tcpSocket:
              port: 2375
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 2375
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 2375
              protocol: TCP
          volumeMounts:
            - mountPath: /scratch
              name: executor-scratch
            - mountPath: /etc/docker/daemon.json
              subPath: daemon.json
              name: docker-config
      volumes:
        - name: executor-scratch
          emptyDir:
            # Ensure we don't cause disk pressure on nodes. This value can be adjusted based on the size of the batch change or code intel requirements.
            # Refer to https://docs.sourcegraph.com/admin/executors/deploy_executors#resource-recommendations for more information
            sizeLimit: 20Gi
        - name: docker-config
          configMap:
            defaultMode: 420
            name: docker-config