sourcegraph:
  image:
    # -- Global docker image tag
    defaultTag: '{{ .Chart.AppVersion }}'
    # -- Global docker image pull policy
    pullPolicy: IfNotPresent
    # -- Global docker image registry or prefix
    repository: index.docker.io/sourcegraph
    # -- When set to true, sourcegraph.image.defaultTag is used as the default defaultTag for all services, instead of service-specific default defaultTags
    useGlobalTagAsDefault: false
  # -- Mount named secrets containing docker credentials
  imagePullSecrets: [ ]
  # -- Add a global label to all resources
  labels: { }
  # -- Set a custom name for the app.kubernetes.io/name annotation
  nameOverride: ""
  # -- Affinity,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity: { }
  # -- NodeSelector,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)
  nodeSelector: { }
  # -- Tolerations,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  tolerations: [ ]
  # -- Add extra annotations to attach to all pods
  podAnnotations: { }
  # -- Add extra labels to attach to all pods
  podLabels: { }


executor:
  enabled: true
  resources:
    limits:
      cpu: "12"
      memory: "30G"
    requests:
      cpu: "8"
      memory: "24G"