sourcegraph:
  image:
    # -- Global docker image tag
    defaultTag: '{{ .Chart.AppVersion }}'
    # -- Global docker image pull policy
    pullPolicy: IfNotPresent
    # -- Global docker image registry or prefix
    repository: index.docker.io/sourcegraph
    # -- When set to true, sourcegraph.image.defaultTag is used as the default defaultTag for all services, instead of service-specific default defaultTags
    useGlobalTagAsDefault: false
  # -- Mount named secrets containing docker credentials
  imagePullSecrets: [ ]
  # -- Add a global label to all resources
  labels: { }
  # -- Set a custom name for the app.kubernetes.io/name annotation
  nameOverride: ""
  # -- Affinity,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity: { }
  # -- NodeSelector,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector)
  nodeSelector: { }
  # -- Tolerations,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  tolerations: [ ]
  # -- Add extra annotations to attach to all pods
  podAnnotations: { }
  # -- Add extra labels to attach to all pods
  podLabels: { }



storageClass:
  create: true
  type: gp3
  provisioner: kubernetes.io/aws-ebs
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Retain


executor:
  enabled: true
  resources:
    limits:
      cpu: "20"
      memory: "48G"
    requests:
      cpu: "8"
      memory: "36G"
  env:
    EXECUTOR_FRONTEND_URL:
      value: "https://sourcegraph.ml.bestegg.com"
    EXECUTOR_FRONTEND_PASSWORD:
      value: "YyJnO5fYlHPi51RMaNNheEcYQ0NxwU3xFXYC"
    EXECUTOR_QUEUE_NAME:
      value: "codeintel"
    EXECUTOR_MAXIMUM_NUM_JOBS:
      value: "2"
    EXECUTOR_USE_FIRECRACKER:
      value: "false"
    EXECUTOR_JOB_NUM_CPUS:
      value: "5"
    EXECUTOR_JOB_MEMORY:
      value: "12G"
    DOCKER_HOST:
      value: "tcp://localhost:2375"
    TMPDIR:
      value: "/scratch"
    EXECUTOR_KEEP_WORKSPACES:
      value: "true"